FROM node


COPY src /app/
COPY package-lock.json /app/
COPY package.json /app/

WORKDIR /app

RUN npm install -g vite

RUN npm install
EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]

